[lightning]
level = "info"
file = "./log/tidb-lightning.log"

[tikv-importer]
backend = "local"
sorted-kv-dir = "/data1/sorted-kv-dir-3"

[mydumper]
data-source-dir = "/data1/tidb-3/"
filter = ['*.*', '!pingcap*.*', '!test*.*', '!mysql*.*', '!sys*.*', '!INFORMATION_SCHEMA*.*', '!PERFORMANCE_SCHEMA*.*', '!METRICS_SCHEMA*.*', '!INSPECTION_SCHEMA*.*']

[tidb]
host = "192.168.0.19"
port = 4000
user = "root"
password = ""
status-port = 10080
pd-addr = "192.168.0.19:2379"

[checkpoint]
dsn = "/tmp/tidb-3_lightning_checkpoint.pb"
