[lightning]
level = "info"
file = "./log/tidb-lightning.log"

[tikv-importer]
backend = "local"
sorted-kv-dir = "/data1/sorted-kv-dir-2"

[mydumper]
data-source-dir = "/data1/sysbench"
filter = [ "*.*", "!pingcap*.*", "!test*.*", "!mysql*.*", "!INFORMATION_SCHEMA*.*", "!PERFORMANCE_SCHEMA*.*", "!METRICS_SCHEMA*.*", "!INSPECTION_SCHEMA*.*",]

[tidb]
host = "192.168.0.14"
port = 4000
user = "root"
password = ""
status-port = 10080
pd-addr = "192.168.0.14:2379"

[checkpoint]
dsn = "/tmp/tidb-2_lightning_checkpoint.pb"
